require 'test_helper'

class PageTest < ActiveSupport::TestCase
  test 'should not save page without title' do
    page = Page.new
    assert_not page.save, 'Saved the page without a title'
  end

  test 'creates a slug based on the title' do
    page = Page.create(title: 'My Page')
    assert_equal 'my-page', page.slug
  end

  test 'user can override the autogenerated slug' do
    page = Page.create(title: 'About my website', slug: 'about')
    assert_equal 'about', page.slug
  end
end
